project:
  type: website
  output-dir: docs

website:
  title: "Jessica Luo"
  navbar:
    background: primary
    search: true
    right:
      - text: home
        href: index.qmd
      - text: about
        href: about.qmd
      - text: CV
        href: research.qmd
      - text: projects
        href: projects.qmd
      - text: contact
        href: contact.qmd

format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    smooth-scroll: true
    toc: false
    link-external-newwindow: true
    other-links:
        - text: LinkedIn
          href: https://www.linkedin.com/in/luo-jessica/
        - text: ResearchGate
          href: https://www.researchgate.net/profile/Jessica-Luo-12
      

# overwrite any render-on-save option
editor:
  render-on-save: true

